#!/usr/bin/env node

var spawn = require('child_process').spawn;
var path = require('path');

var child = spawn('node_modules/.bin/mocha-phantomjs', [
  'http://localhost:3000/test/index.html',
  '-p', path.join('.', 'node_modules', '.bin', 'phantomjs'),
  '--timeout', '25000',
  '--hooks', 'phantom_hooks.js'
]);

child.stdout.on('data', function(data) {
  console.log('stdout: ' + data);
});

child.stderr.on('data', function(data) {
  console.log('stderr: ' + data);
});

child.on('close', function (code) {
  console.log('Mocha process exited with code ' + code);
  if (code > 0) {
    process.exit(1);
  }
});
