#!/usr/bin/env node

var GeoPackageOptimizer = require('./index.js');

var fs = require('fs')
  , async = require('async')
  , GeoPackageAPI = require('@ngageoint/geopackage');

console.log('GeoPackage Optimizer For Mobile Clients');

var geoPackageFile = process.argv[2];
var outputGeoPackageFile = process.argv[3];

if (!geoPackageFile || !outputGeoPackageFile) {
  console.log('Usage: mobile-optimizer <geoPackageToProcess> <geoPackageToWrite>')
  process.exit(1);
}

fs.stat(geoPackageFile, function(err, stats) {
  if (err || !stats || !stats.isFile()) {
    console.log('File does not exist.', geoPackageFile);
    process.exit(1);
  }
  return GeoPackageAPI.open(geoPackageFile)
  .then(function(inputGeoPackage) {
    console.log('Processing %s', geoPackageFile);
    return GeoPackageAPI.create(outputGeoPackageFile)
    .then(function(outputGeoPackage) {
      console.log('Writing mobile optimized GeoPackage to %s', outputGeoPackageFile);
      console.log('inputGeoPackage', inputGeoPackage);
      console.log('outputGeoPackage', outputGeoPackage);
      return GeoPackageOptimizer(inputGeoPackage, outputGeoPackage)
      .then(function() {
        console.log('Optimization Complete, optimized file: %s', outputGeoPackageFile);
        process.exit(0);
      });
    });
  });
});
