#!/usr/bin/env node

const ShapeFileToGeoPackage = require('./built/index');
const path = require('path');

console.log('Shapefile to GeoPackage Converter');

const shapefileFile = path.resolve(process.cwd(), process.argv[2]);
const geoPackageFile = path.resolve(process.cwd(), process.argv[3]);

console.log('Converting %s to %s', shapefileFile, geoPackageFile);
ShapeFileToGeoPackage.convert(
  {
    shapefile: shapefileFile,
    geopackage: geoPackageFile,
  },
  function(status, callback) {
    callback();
  },
  function(err, result) {
    if (err) {
      console.log('File conversion failed with error: ', err);
    } else {
      console.log('File conversion complete');
      console.log('Converted %s to %s', shapefileFile, geoPackageFile);
    }
  },
);
