#!/usr/bin/env node

const MBTilesToGeoPackage = require('./built/index');
const path = require('path');

console.log('MBTiles to GeoPackage Converter');

const mbtilesFile = path.resolve(process.cwd(), process.argv[2]);
const geoPackageFile = path.resolve(process.cwd(), process.argv[3]);

console.log('Converting %s to %s', mbtilesFile, geoPackageFile);
MBTilesToGeoPackage.convert(
  {
    mbtiles: mbtilesFile,
    geopackage: geoPackageFile,
  },
  function(status, callback) {
    callback();
  },
  function(err, result) {
    if (err) {
      console.log('File conversion failed with error: ', err);
    } else {
      console.log('File conversion complete');
      console.log('Converted %s to %s', mbtilesFile, geoPackageFile);
    }
  },
);
