#!/usr/bin/env node

const { KMLToGeoPackage } = require('./built/index');
const path = require('path');

console.log('KML to GeoPackage Converter');

const filePath = path.resolve(process.cwd(), process.argv[2]);
const geoPackageFile = path.resolve(process.cwd(), process.argv[3]);

const options = {
  kmlOrKmzPath: filePath,
  isKMZ: filePath.endsWith('kmz'),
  mainTableName: path.basename(filePath, path.extname(filePath)),
  geoPackage: process.argv[3],
};
console.log('Converting %s to %s', options, geoPackageFile);

new KMLToGeoPackage()
  .convert(options, a => {
    console.log(a.status);
  })
  .then(function(result) {
    console.log('File conversion complete');
    console.log('Converted %s to %s', options, geoPackageFile);
  });